#!/usr/bin/env python3
import json
import sys

def mock_generate_listing(marketplace, brand, product_name, features, keywords):
    """
    Demonstrates the structured JSON output generated by GTX Listing Studio AI
    for Amazon, Walmart, Etsy, Shopify, eBay, and Noon.
    """
    title = f"{brand} {product_name} | {features[0]} | {features[1]} ({marketplace.upper()} Edition)"
    
    bullet_points = [
        f"PREMIUM QUALITY: Engineered by {brand} with {features[0]} for maximum durability.",
        f"HIGH PERFORMANCE: Features {features[1]} ensuring peak efficiency during use.",
        f"VERSATILE & CONVENIENT: Designed with {features[2] if len(features) > 2 else 'lightweight materials'} for everyday convenience.",
        f"ECO-FRIENDLY & SAFE: Non-toxic materials meeting global compliance standards.",
        f"CUSTOMER SATISFACTION GUARANTEED: Backed by {brand}'s dedicated customer support."
    ]
    
    description = (
        f"Elevate your daily routine with the all-new {product_name} from {brand}. "
        f"Specially crafted for {marketplace.capitalize()} shoppers, this product combines {', '.join(features)}. "
        f"Whether for personal use or as a thoughtful gift, {brand} delivers unmatched reliability and performance."
    )
    
    return {
        "status": "success",
        "marketplace": marketplace,
        "listing": {
            "productTitle": title,
            "bulletPoints": bullet_points,
            "description": description,
            "backendKeywords": keywords + [f"{brand.lower()} {k}" for k in keywords],
            "seoScore": 94,
            "metaTitle": f"{product_name} by {brand} - Buy Online",
            "metaDescription": f"Discover {product_name} by {brand}. Top rated on {marketplace.capitalize()} with free delivery options.",
            "imageSuggestions": [
                "Main Hero Image: Product on clean white background",
                "Lifestyle Image: Product being used in action",
                "Infographic: Key dimensions and feature breakdown"
            ],
            "faqs": [
                {"question": "Is this product durable?", "answer": "Yes, built with high-grade materials."},
                {"question": "What is the warranty period?", "answer": "Includes a 1-year manufacturer warranty."}
            ]
        }
    }

if __name__ == "__main__":
    print("==================================================")
    print(" GTX LISTING STUDIO AI - LOCAL DEMO ENGINE")
    print("==================================================")
    
    mp = sys.argv[1] if len(sys.argv) > 1 else "amazon"
    
    sample_input = {
        "marketplace": mp,
        "brand": "Ethletico",
        "productName": "Collapsible Silicone Water Bottle",
        "features": ["BPA-Free Food Grade Silicone", "500ml Foldable Design", "Leakproof Twist Cap"],
        "keywords": ["sports bottle", "gym bottle", "collapsible bottle", "travel flask"]
    }
    
    result = mock_generate_listing(
        sample_input["marketplace"],
        sample_input["brand"],
        sample_input["productName"],
        sample_input["features"],
        sample_input["keywords"]
    )
    
    print(json.dumps(result, indent=2))
